language: node_js
node_js:
  - "10.4.0"
cache:
  directories:
  - node_modules
script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $advanced
  local-dir: dist
  target-branch: gh-pages
  on:
      branch: week5